@baseURL=http://localhost:5555

# @name test
POST {{baseURL}}/restaurants
Content-Type: application/json

{
  "restaurantName": "JajaPizzaria",
  "managerName": "Maria Fernanda",
  "email": "mf@nl.com",
  "phone": "123456458"
}